import type { Product } from "@/components/product-card";

const ph = (text: string, bg = "1a1a1a", fg = "f1ece1") =>
  `https://placehold.co/800x1000/${bg}/${fg}/png?text=${encodeURIComponent(text)}&font=oswald`;

export const PRODUCTS: Product[] = [
  {
    handle: "atlas-work-jacket",
    name: "Atlas Work Jacket",
    price: 245,
    currency: "USD",
    category: "Outerwear",
    front: ph("ATLAS\\nFRONT"),
    back: ph("ATLAS\\nBACK", "0a0a0a"),
    badge: "Drop 01",
  },
  {
    handle: "loop-cardigan",
    name: "Loop Knit Cardigan",
    price: 180,
    currency: "USD",
    category: "Knitwear",
    front: ph("LOOP\\nFRONT", "2b2b2b"),
    back: ph("LOOP\\nBACK", "111111"),
  },
  {
    handle: "haze-tee",
    name: "Haze Pocket Tee",
    price: 65,
    currency: "USD",
    category: "Tops",
    front: ph("HAZE\\nFRONT", "1f1f1f"),
    back: ph("HAZE\\nBACK", "0f0f0f"),
  },
  {
    handle: "rope-cargo",
    name: "Rope Cargo Pant",
    price: 195,
    currency: "USD",
    category: "Bottoms",
    front: ph("ROPE\\nFRONT", "2a2418"),
    back: ph("ROPE\\nBACK", "1c1810"),
    badge: "New",
  },
  {
    handle: "void-hoodie",
    name: "Void Heavyweight Hoodie",
    price: 165,
    currency: "USD",
    category: "Tops",
    front: ph("VOID\\nFRONT", "0a0a0a"),
    back: ph("VOID\\nBACK", "1a1a1a"),
  },
  {
    handle: "static-cap",
    name: "Static Six-Panel Cap",
    price: 55,
    currency: "USD",
    category: "Accessories",
    front: ph("STATIC\\nFRONT", "121212"),
    back: ph("STATIC\\nBACK", "0c0c0c"),
    soldOut: true,
  },
  {
    handle: "pulse-shorts",
    name: "Pulse Mesh Shorts",
    price: 85,
    currency: "USD",
    category: "Bottoms",
    front: ph("PULSE\\nFRONT", "1c1c1c"),
    back: ph("PULSE\\nBACK", "0d0d0d"),
  },
  {
    handle: "ember-scarf",
    name: "Ember Wool Scarf",
    price: 95,
    currency: "USD",
    category: "Accessories",
    front: ph("EMBER\\nFRONT", "3a1d10"),
    back: ph("EMBER\\nBACK", "230f08"),
  },
  {
    handle: "north-varsity",
    name: "North Wool Varsity",
    price: 385,
    currency: "USD",
    category: "Outerwear",
    front: ph("NORTH\\nFRONT", "0e1a2a"),
    back: ph("NORTH\\nBACK", "07101c"),
    badge: "Drop 01",
  },
  {
    handle: "ash-overshirt",
    name: "Ash Brushed Overshirt",
    price: 165,
    currency: "USD",
    category: "Tops",
    front: ph("ASH\\nFRONT", "2c2a26"),
    back: ph("ASH\\nBACK", "1a1916"),
  },
  {
    handle: "drift-jean",
    name: "Drift Loose Jean",
    price: 175,
    currency: "USD",
    category: "Bottoms",
    front: ph("DRIFT\\nFRONT", "1a2030"),
    back: ph("DRIFT\\nBACK", "0e1320"),
  },
  {
    handle: "halo-beanie",
    name: "Halo Ribbed Beanie",
    price: 45,
    currency: "USD",
    category: "Accessories",
    front: ph("HALO\\nFRONT", "111111"),
    back: ph("HALO\\nBACK", "060606"),
  },
  {
    handle: "echo-tee",
    name: "Echo Long-Sleeve Tee",
    price: 75,
    currency: "USD",
    category: "Tops",
    front: ph("ECHO\\nFRONT", "1d1d1d"),
    back: ph("ECHO\\nBACK", "0e0e0e"),
    badge: "New",
  },
  {
    handle: "iron-tote",
    name: "Iron Canvas Tote",
    price: 60,
    currency: "USD",
    category: "Accessories",
    front: ph("IRON\\nFRONT", "1f1c14"),
    back: ph("IRON\\nBACK", "100e0a"),
  },
  {
    handle: "moss-mock-knit",
    name: "Moss Mock-Neck Knit",
    price: 195,
    currency: "USD",
    category: "Knitwear",
    front: ph("MOSS\\nFRONT", "1a2018"),
    back: ph("MOSS\\nBACK", "0c100c"),
  },
  {
    handle: "rust-trucker",
    name: "Rust Trucker Jacket",
    price: 220,
    currency: "USD",
    category: "Outerwear",
    front: ph("RUST\\nFRONT", "2c1a12"),
    back: ph("RUST\\nBACK", "180c08"),
  },
  {
    handle: "fade-cargo-short",
    name: "Fade Cargo Short",
    price: 105,
    currency: "USD",
    category: "Bottoms",
    front: ph("FADE\\nFRONT", "26241c"),
    back: ph("FADE\\nBACK", "13110d"),
  },
  {
    handle: "sable-cardigan",
    name: "Sable Cable Cardigan",
    price: 225,
    currency: "USD",
    category: "Knitwear",
    front: ph("SABLE\\nFRONT", "0a0908"),
    back: ph("SABLE\\nBACK", "050403"),
    soldOut: true,
  },
  {
    handle: "neon-belt",
    name: "Neon Webbing Belt",
    price: 50,
    currency: "USD",
    category: "Accessories",
    front: ph("NEON\\nFRONT", "1a1a1a"),
    back: ph("NEON\\nBACK", "0e0e0e"),
  },
  {
    handle: "kiln-graphic-tee",
    name: "Kiln Graphic Tee",
    price: 75,
    currency: "USD",
    category: "Tops",
    front: ph("KILN\\nFRONT", "1c1410"),
    back: ph("KILN\\nBACK", "0e0908"),
    badge: "Drop 01",
  },
];

export function getProduct(handle: string) {
  return PRODUCTS.find((p) => p.handle === handle);
}
